export const FETCH_SHOP_PROMOTION = {
	FETCH_SHOP_PROMOTION_INITIAL: "FETCH_SHOP_PROMOTION_INITIAL",
	FETCH_SHOP_PROMOTION_FAIL: "FETCH_SHOP_PROMOTION_FAIL",
	FETCH_SHOP_PROMOTION_LOADING: "FETCH_SHOP_PROMOTION_LOADING",
	FETCH_SHOP_PROMOTION_SUCCESS: "FETCH_SHOP_PROMOTION_SUCCESS"
}