export const FETCH_PROFILE = {
	FETCH_PROFILE_INITIAL: "FETCH_PROFILE_INITIAL",
	FETCH_PROFILE_FAIL: "FETCH_PROFILE_FAIL",
	FETCH_PROFILE_LOADING: "FETCH_PROFILE_LOADING",
	FETCH_PROFILE_SUCCESS: "FETCH_PROFILE_SUCCESS"
}


