export const FETCH_VARIATION_OPTIONS={
	FETCH_VARIATION_OPTIONS_INITIAL: "FETCH_VARIATION_OPTIONS_INITIAL",
	FETCH_VARIATION_OPTIONS_FAIL: "FETCH_VARIATION_OPTIONS_FAIL",
	FETCH_VARIATION_OPTIONS_LOADING: "FETCH_VARIATION_OPTIONS_LOADING",
	FETCH_VARIATION_OPTIONS_SUCCESS: "FETCH_VARIATION_OPTIONS_SUCCESS"
}