export const FETCH_PRODUCT_VARIATION = {
	FETCH_PRODUCT_VARIATION_INITIAL: "FETCH_PRODUCT_VARIATION_INITIAL",
	FETCH_PRODUCT_VARIATION_FAIL: "FETCH_PRODUCT_VARIATION_FAIL",
	FETCH_PRODUCT_VARIATION_LOADING: "FETCH_PRODUCT_VARIATION_LOADING",
	FETCH_PRODUCT_VARIATION_SUCCESS: "FETCH_PRODUCT_VARIATION_SUCCESS"
}
export const FETCH_VARIATIONS={
	FETCH_VARIATIONS_INITIAL: "FETCH_VARIATIONS_INITIAL",
	FETCH_VARIATIONS_FAIL: "FETCH_VARIATIONS_FAIL",
	FETCH_VARIATIONS_LOADING: "FETCH_VARIATIONS_LOADING",
	FETCH_VARIATIONS_SUCCESS: "FETCH_VARIATIONS_SUCCESS"
}
export const FETCH_RESULT_VARIATION={
	FETCH_RESULT_VARIATION_INITIAL: "FETCH_RESULT_VARIATION_INITIAL",
	FETCH_RESULT_VARIATION_FAIL: "FETCH_RESULT_VARIATION_FAIL",
	FETCH_RESULT_VARIATION_LOADING: "FETCH_RESULT_VARIATION_LOADING",
	FETCH_RESULT_VARIATION_SUCCESS: "FETCH_RESULT_VARIATION_SUCCESS"
}
export const FETCH_BY_ID_VARIATION={
	FETCH_BY_ID_VARIATION_INITIAL: "FETCH_BY_ID_VARIATION_INITIAL",
	FETCH_BY_ID_VARIATION_FAIL: "FETCH_BY_ID_VARIATION_FAIL",
	FETCH_BY_ID_VARIATION_LOADING: "FETCH_BY_ID_VARIATION_LOADING",
	FETCH_BY_ID_VARIATION_SUCCESS: "FETCH_BY_ID_VARIATION_SUCCESS"
}
export const FETCH_DELETE_VARIATION={
	FETCH_DELETE_VARIATION_INITIAL: "FETCH_DELETE_VARIATION_INITIAL",
	FETCH_DELETE_VARIATION_FAIL: "FETCH_DELETE_VARIATION_FAIL",
	FETCH_DELETE_VARIATION_LOADING: "FETCH_DELETE_VARIATION_LOADING",
	FETCH_DELETE_VARIATION_SUCCESS: "FETCH_DELETE_VARIATION_SUCCESS"
}
export const FETCH_EDIT_VARIATION={
	FETCH_EDIT_VARIATION_INITIAL: "FETCH_EDIT_VARIATION_INITIAL",
	FETCH_EDIT_VARIATION_FAIL: "FETCH_EDIT_VARIATION_FAIL",
	FETCH_EDIT_VARIATION_LOADING: "FETCH_EDIT_VARIATION_LOADING",
	FETCH_EDIT_VARIATION_SUCCESS: "FETCH_EDIT_VARIATION_SUCCESS"
}
export const FETCH_SAVE_VARIATION={
	FETCH_SAVE_VARIATION_INITIAL: "FETCH_SAVE_VARIATION_INITIAL",
	FETCH_SAVE_VARIATION_FAIL: "FETCH_SAVE_VARIATION_FAIL",
	FETCH_SAVE_VARIATION_LOADING: "FETCH_SAVE_VARIATION_LOADING",
	FETCH_SAVE_VARIATION_SUCCESS: "FETCH_SAVE_VARIATION_SUCCESS"
}