export const FETCH_REFRESH_TOKEN = {
	FETCH_REFRESH_TOKEN_INITIAL: "FETCH_REFRESH_TOKEN_INITIAL",
	FETCH_REFRESH_TOKEN_FAIL: "FETCH_REFRESH_TOKEN_FAIL",
	FETCH_REFRESH_TOKEN_LOADING: "FETCH_REFRESH_TOKEN_LOADING",
	FETCH_REFRESH_TOKEN_SUCCESS: "FETCH_REFRESH_TOKEN_SUCCESS"
}